---
# 开发环境配置文件
environment: development
app_name: AutoReportAI-Dev
version: "1.0.0"
debug: true

# 数据库配置
database:
  host: localhost
  port: 5432
  database: autoreport_dev
  username: postgres
  password: password
  pool_size: 5
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 3600
  ssl_mode: disable

# Redis配置
redis:
  host: localhost
  port: 6379
  password: null
  database: 2
  max_connections: 10
  timeout: 5
  ssl: false

# 安全配置
security:
  jwt_secret_key: dev-secret-key-not-for-production
  jwt_algorithm: HS256
  jwt_expiration_time: 7200
  cors_origins:
    - "*"
  allowed_hosts:
    - "*"
  rate_limit_per_minute: 1000

# MCP编排器配置
mcp_orchestrator:
  max_concurrent_requests: 20
  request_timeout: 120
  circuit_breaker_failure_threshold: 3
  circuit_breaker_recovery_timeout: 30
  load_balancing_strategy: round_robin
  enable_metrics: true
  enable_tracing: false
  cache_ttl: 60
  batch_size: 5
  
  # 性能优化
  enable_connection_pooling: true
  max_pool_size: 20
  pool_timeout: 15
  
  # 监控配置
  health_check_interval: 60
  metrics_export_interval: 120
  log_level: DEBUG

# MCP服务器配置
mcp_servers:
  - name: semantic-analysis
    host: localhost
    port: 8001
    protocol: ws
    max_connections: 10
    timeout: 60
    retry_count: 2
    health_check_interval: 60
    enabled: true
    priority: 1
    tags:
      - analysis
      - semantic
      - dev

  - name: sql-generation
    host: localhost
    port: 8002
    protocol: ws
    max_connections: 10
    timeout: 45
    retry_count: 2
    health_check_interval: 60
    enabled: true
    priority: 1
    tags:
      - sql
      - generation
      - dev

  - name: data-execution
    host: localhost
    port: 8003
    protocol: ws
    max_connections: 5
    timeout: 120
    retry_count: 1
    health_check_interval: 60
    enabled: true
    priority: 2
    tags:
      - data
      - execution
      - dev

  - name: quality-assessment
    host: localhost
    port: 8004
    protocol: ws
    max_connections: 5
    timeout: 90
    retry_count: 2
    health_check_interval: 60
    enabled: true
    priority: 1
    tags:
      - quality
      - assessment
      - dev

# 日志配置
log_level: DEBUG
log_file: null
enable_structured_logging: false

# 健康检查配置
enable_health_checks: true
health_check_path: /health
metrics_path: /metrics

# 部署配置
workers: 1
worker_timeout: 15
max_requests_per_worker: 100