---
# 预发布环境配置文件
environment: staging
app_name: AutoReportAI-Staging
version: "1.0.0"
debug: false

# 数据库配置
database:
  host: postgres-staging
  port: 5432
  database: autoreport_staging
  username: postgres
  password: ${DB_PASSWORD}
  pool_size: 10
  max_overflow: 15
  pool_timeout: 30
  pool_recycle: 3600
  ssl_mode: prefer

# Redis配置
redis:
  host: redis-staging
  port: 6379
  password: ${REDIS_PASSWORD}
  database: 1
  max_connections: 25
  timeout: 5
  ssl: false

# 安全配置
security:
  jwt_secret_key: ${JWT_SECRET_KEY}
  jwt_algorithm: HS256
  jwt_expiration_time: 3600
  cors_origins:
    - "https://staging.yourdomain.com"
    - "http://localhost:3000"
  allowed_hosts:
    - "staging.yourdomain.com"
    - "localhost"
  rate_limit_per_minute: 60

# MCP编排器配置
mcp_orchestrator:
  max_concurrent_requests: 50
  request_timeout: 300
  circuit_breaker_failure_threshold: 5
  circuit_breaker_recovery_timeout: 60
  load_balancing_strategy: round_robin
  enable_metrics: true
  enable_tracing: true
  cache_ttl: 300
  batch_size: 10
  
  # 性能优化
  enable_connection_pooling: true
  max_pool_size: 100
  pool_timeout: 30
  
  # 监控配置
  health_check_interval: 30
  metrics_export_interval: 60
  log_level: DEBUG

# MCP服务器配置
mcp_servers:
  - name: semantic-analysis
    host: mcp-semantic-analysis-staging
    port: 8001
    protocol: ws
    max_connections: 25
    timeout: 60
    retry_count: 3
    health_check_interval: 30
    enabled: true
    priority: 1
    tags:
      - analysis
      - semantic

  - name: sql-generation
    host: mcp-sql-generation-staging
    port: 8002
    protocol: ws
    max_connections: 20
    timeout: 45
    retry_count: 3
    health_check_interval: 30
    enabled: true
    priority: 1
    tags:
      - sql
      - generation

  - name: data-execution
    host: mcp-data-execution-staging
    port: 8003
    protocol: ws
    max_connections: 15
    timeout: 120
    retry_count: 2
    health_check_interval: 30
    enabled: true
    priority: 2
    tags:
      - data
      - execution

  - name: quality-assessment
    host: mcp-quality-assessment-staging
    port: 8004
    protocol: ws
    max_connections: 10
    timeout: 90
    retry_count: 3
    health_check_interval: 30
    enabled: true
    priority: 1
    tags:
      - quality
      - assessment

# 日志配置
log_level: DEBUG
log_file: /app/logs/app.log
enable_structured_logging: true

# 健康检查配置
enable_health_checks: true
health_check_path: /health
metrics_path: /metrics

# 部署配置
workers: 4
worker_timeout: 30
max_requests_per_worker: 1000