version: '3.8'

services:
  test_db:
    image: postgres:15
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: test_app
    ports:
      - "5433:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d test_app"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend_test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - TEST_DATABASE_URL=postgresql://testuser:testpassword@test_db:5432/test_app
      - ENVIRONMENT=test
    depends_on:
      test_db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: pytest --cov=app --cov-report=xml --cov-report=term-missing
    profiles:
      - test

volumes:
  test_db_data: 