# AutoReportAI Docker Compose Configuration
# 
# 主要配置文件位于 ./docker/docker-compose.yml
# 请使用以下命令启动服务:
#   docker-compose -f docker/docker-compose.yml up -d
#
# 或者复制环境变量模板:
#   cp docker/.env.template .env
#   docker-compose -f docker/docker-compose.yml --env-file .env up -d

version: '3.8'

# 这是一个简化的引用文件，实际配置请查看 docker/ 目录
# 建议直接使用: docker-compose -f docker/docker-compose.yml up -d

services:
  placeholder:
    image: hello-world
    command: echo "请使用 docker-compose -f docker/docker-compose.yml up -d 启动服务"