"""Add ETLJob model

Revision ID: 2d1a3b4c5d6e
Revises: 
Create Date: 2024-08-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d1a3b4c5d6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_jobs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source_data_source_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('destination_table_name', sa.String(), nullable=False),
    sa.Column('transformation_script', sa.Text(), nullable=False),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etl_jobs_destination_table_name'), 'etl_jobs', ['destination_table_name'], unique=True)
    op.create_index(op.f('ix_etl_jobs_name'), 'etl_jobs', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etl_jobs_name'), table_name='etl_jobs')
    op.drop_index(op.f('ix_etl_jobs_destination_table_name'), table_name='etl_jobs')
    op.drop_table('etl_jobs')
    # ### end Alembic commands ### 