"""add_missing_user_profile_fields

Revision ID: 9aab47d2e221
Revises: 721a708f5fa0
Create Date: 2025-07-15 18:29:02.401095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aab47d2e221'
down_revision: Union[str, Sequence[str], None] = '721a708f5fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('report_notifications', sa.Boolean(), nullable=True))
    op.add_column('user_profiles', sa.Column('system_notifications', sa.Boolean(), nullable=True))
    op.add_column('user_profiles', sa.Column('default_storage_days', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('auto_cleanup_enabled', sa.Boolean(), nullable=True))
    op.add_column('user_profiles', sa.Column('default_ai_provider', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('dashboard_layout', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'dashboard_layout')
    op.drop_column('user_profiles', 'default_ai_provider')
    op.drop_column('user_profiles', 'auto_cleanup_enabled')
    op.drop_column('user_profiles', 'default_storage_days')
    op.drop_column('user_profiles', 'system_notifications')
    op.drop_column('user_profiles', 'report_notifications')
    # ### end Alembic commands ###
