"""Add missing doris fields to data_sources

Revision ID: a89cde1cb970
Revises: 5990cd7f4f40
Create Date: 2025-07-25 15:45:14.690624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a89cde1cb970'
down_revision: Union[str, Sequence[str], None] = '5990cd7f4f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('doris_fe_hosts', sa.JSON(), nullable=True))
    op.add_column('data_sources', sa.Column('doris_be_hosts', sa.JSON(), nullable=True))
    op.add_column('data_sources', sa.Column('doris_http_port', sa.Integer(), nullable=True))
    op.add_column('data_sources', sa.Column('doris_query_port', sa.Integer(), nullable=True))
    op.add_column('data_sources', sa.Column('doris_database', sa.String(), nullable=True))
    op.add_column('data_sources', sa.Column('doris_username', sa.String(), nullable=True))
    op.add_column('data_sources', sa.Column('doris_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'doris_password')
    op.drop_column('data_sources', 'doris_username')
    op.drop_column('data_sources', 'doris_database')
    op.drop_column('data_sources', 'doris_query_port')
    op.drop_column('data_sources', 'doris_http_port')
    op.drop_column('data_sources', 'doris_be_hosts')
    op.drop_column('data_sources', 'doris_fe_hosts')
    # ### end Alembic commands ###
