"""restore_complete_relationships_and_foreign_keys

Revision ID: ab1d30882af3
Revises: 6285aa9d6358
Create Date: 2025-07-15 18:16:10.389722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1d30882af3'
down_revision: Union[str, Sequence[str], None] = '6285aa9d6358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 首先添加可为空的user_id列
    op.add_column('enhanced_data_sources', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('etl_jobs', sa.Column('user_id', sa.UUID(), nullable=True))
    
    # 为现有记录设置默认的user_id（使用现有的第一个用户）
    op.execute("""
        UPDATE enhanced_data_sources 
        SET user_id = (SELECT id FROM users LIMIT 1)
        WHERE user_id IS NULL
    """)
    
    op.execute("""
        UPDATE etl_jobs 
        SET user_id = (SELECT id FROM users LIMIT 1)
        WHERE user_id IS NULL
    """)
    
    # 然后设置为非空
    op.alter_column('enhanced_data_sources', 'user_id', nullable=False)
    op.alter_column('etl_jobs', 'user_id', nullable=False)
    
    # 创建外键约束
    op.create_foreign_key(None, 'enhanced_data_sources', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'etl_jobs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'placeholder_mappings', 'templates', ['template_id'], ['id'])
    op.alter_column('tasks', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('templates', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_profiles', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint(None, 'user_profiles', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.alter_column('user_profiles', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('templates', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('tasks', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'placeholder_mappings', type_='foreignkey')
    op.drop_constraint(None, 'etl_jobs', type_='foreignkey')
    op.drop_column('etl_jobs', 'user_id')
    op.drop_constraint(None, 'enhanced_data_sources', type_='foreignkey')
    op.drop_column('enhanced_data_sources', 'user_id')
    # ### end Alembic commands ###
