"""add connection_string to data_source

Revision ID: add_connection_string
Revises: 2d1a3b4c5d6e
Create Date: 2024-12-19 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_connection_string'
down_revision = '2d1a3b4c5d6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('connection_string', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'connection_string')
    # ### end Alembic commands ### 