"""create placeholder mapping table

Revision ID: placeholder_mapping_001
Revises: 
Create Date: 2025-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'placeholder_mapping_001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placeholder_mapping_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placeholder_signature', sa.String(length=255), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('matched_field', sa.String(length=255), nullable=False),
    sa.Column('confidence_score', sa.DECIMAL(precision=3, scale=2), nullable=False),
    sa.Column('transformation_config', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['enhanced_data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placeholder_signature')
    )
    op.create_index(op.f('ix_placeholder_mapping_cache_id'), 'placeholder_mapping_cache', ['id'], unique=False)
    op.create_index(op.f('ix_placeholder_mapping_cache_placeholder_signature'), 'placeholder_mapping_cache', ['placeholder_signature'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_placeholder_mapping_cache_placeholder_signature'), table_name='placeholder_mapping_cache')
    op.drop_index(op.f('ix_placeholder_mapping_cache_id'), table_name='placeholder_mapping_cache')
    op.drop_table('placeholder_mapping_cache')
    # ### end Alembic commands ###