info:
  description: "\n        ## AutoReportAI 智能报告生成系统API\n\n        这是一个基于AI的智能报告生成系统，提供以下核心功能：\n\
    \        \n        ### \U0001F510 认证与授权\n        * 用户注册、登录、密码重置\n        * JWT\
    \ token认证\n        * 角色权限管理\n        \n        ### \U0001F4CA 数据源管理\n        *\
    \ 多种数据源连接（数据库、API、文件）\n        * 数据源配置与验证\n        * 数据预处理和清洗\n        \n    \
    \    ### \U0001F916 AI服务集成\n        * 多AI提供商支持（OpenAI、Claude、本地模型）\n        *\
    \ 智能数据分析\n        * 自动图表生成\n        \n        ### \U0001F4DD 报告生成\n        * 模板化报告生成\n\
    \        * 智能占位符匹配\n        * 多格式输出支持\n        \n        ### \U0001F504 ETL任务管理\n\
    \        * 数据提取、转换、加载\n        * 任务调度与监控\n        * 数据质量检查\n        \n       \
    \ ## \U0001F680 快速开始\n        \n        1. 获取API访问令牌\n        2. 配置数据源\n     \
    \   3. 创建报告模板\n        4. 生成报告\n        \n        ## \U0001F4CB API版本\n      \
    \  \n        当前版本：v1.0.0\n        \n        ## \U0001F517 相关链接\n        \n   \
    \     * [GitHub仓库](https://github.com/your-org/AutoReportAI)\n        * [用户指南](https://docs.autoreportai.com)\n\
    \        * [API最佳实践](https://docs.autoreportai.com/api/best-practices)\n     \
    \   "
  title: AutoReportAI API
  version: 1.0.0
openapi: 3.1.0
paths: {}
servers:
- description: 生产环境
  url: https://api.autoreportai.com
- description: 测试环境
  url: https://staging-api.autoreportai.com
- description: 本地开发环境
  url: http://localhost:8000
tags:
- description: 用户认证与授权相关操作
  name: 认证
- description: 用户信息管理
  name: 用户管理
- description: 数据源连接与管理
  name: 数据源
- description: AI提供商与AI服务管理
  name: AI服务
- description: 报告模板管理
  name: 模板
- description: 任务创建与管理
  name: 任务
- description: 数据提取、转换、加载
  name: ETL
- description: 报告生成与历史记录
  name: 报告
- description: 系统状态与健康检查
  name: 系统
